# Blender Add-on Manifest for Blender 4.2+
schema_version = "1.0.0"
# Basic add-on information
id = "nfc_card_keychain_generator"
version = "1.0.0"
name = "NFC Card & Keychain Generator"
tagline = "Generate customizable 3D-printable cards, tags, and keychains"
maintainer = "Clonephaze <jack@clonecore.net>"
type = "add-on"

# Blender version compatibility - currently no plans to support older versions
blender_version_min = "4.2.0"

# License and website information
license = ['SPDX:GPL-3.0-or-later']
website = "https://github.com/clonephaze/NFC-Card-Keychain-w--QR-or-Logo-Placer"
copyright = [
    "2025 Clonephaze",
]

# Tags for categorization in Blender's add-on browser
tags = [
    "3D View",
	"Modeling",
	"Object",
	"User Interface",
]

# Detailed description
description = """
A comprehensive add-on for generating customizable 3D-printable cards, tags, and keychains.

Features:
- Base shapes: cards, circles, with optional keychain loops
- Configurable dimensions with rounded corners
- NFC slots and magnet hole cutouts with taper control
- Edge beveling with adjustable segments
- Logo/QR code placement (automated and manual workflows)
- SVG import pipeline for custom graphics
- Built-in QR code generation

Uses Geometry Nodes and modifiers for maximum flexibility and performance.
"""
permissions = [
    "files",  # For custom SVG import and file saving operations
]

# Dependencies - segno library will be bundled as a wheel
wheels = [
    "./wheels/segno-1.6.6-py3-none-any.whl",
]