schema_version = "1.0.0"
id = "nfc_card_keychain_generator"
version = "1.1.5"
name = "NFC Card and Keychain Generator"
tagline = "Generate customizable 3D-printable cards, tags, and keychains"
maintainer = "Clonephaze <jack@clonecore.net>"
type = "add-on"
blender_version_min = "4.2.0"
license = ['SPDX:GPL-3.0-or-later']
website = "https://github.com/Clonephaze/nfc-keychain-generator-blender-addon"
copyright = [
    "2025 Clonephaze",
]
tags = [
	"Modeling",
	"Object",
]

description = """
A comprehensive add-on for generating customizable 3D-printable cards, tags, and keychains.

Features:
- Base shapes: cards, circles, with optional keychain loops
- Configurable dimensions with rounded corners
- NFC slots and magnet hole cutouts with taper control
- Edge beveling with adjustable segments
- Logo/QR code placement (automated and manual workflows)
- SVG import pipeline for custom graphics
- Built-in QR code generation

Uses Geometry Nodes and modifiers for maximum flexibility and performance.
"""
wheels = [
    "./wheels/segno-1.6.6-py3-none-any.whl",
]
[permissions]
    files = "For custom SVG import and file saving operations"
